- hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started

    - name: Copiar archivos HTML
      copy:
        src: /path/to/index.html
        dest: /var/www/html/index.html
